"""empty message

Revision ID: 1de50df49d64
Revises: dd43afb82b70
Create Date: 2024-05-16 12:42:28.168912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de50df49d64'
down_revision = 'dd43afb82b70'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepare_transfer_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_locked_amount', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('max_locked_amount', sa.BigInteger(), nullable=False))
        batch_op.add_column(sa.Column('final_interest_rate_ts', sa.TIMESTAMP(timezone=True), nullable=False))
        batch_op.drop_column('locked_amount')
        batch_op.drop_column('min_interest_rate')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prepare_transfer_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_interest_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('locked_amount', sa.BIGINT(), autoincrement=False, nullable=False))
        batch_op.drop_column('final_interest_rate_ts')
        batch_op.drop_column('max_locked_amount')
        batch_op.drop_column('min_locked_amount')

    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

