"""empty message

Revision ID: 22c78b7cb0d7
Revises: c442e0862585
Create Date: 2024-06-12 16:22:51.261473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c78b7cb0d7'
down_revision = 'c442e0862585'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transfer_attempt',
    sa.Column('from_collector_id', sa.BigInteger(), nullable=False),
    sa.Column('debtor_id', sa.BigInteger(), nullable=False),
    sa.Column('turn_id', sa.Integer(), nullable=False),
    sa.Column('to_creditor_id', sa.BigInteger(), nullable=False),
    sa.Column('is_dispatching', sa.BOOLEAN(), nullable=False),
    sa.Column('nominal_amount', sa.FLOAT(), nullable=False),
    sa.Column('collection_started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('inserted_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('scheduled_for', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('attempted_at', sa.TIMESTAMP(timezone=True), nullable=True, comment='The timestamp of the sent `PrepareTransfer` SMP message.'),
    sa.Column('coordinator_request_id', sa.BigInteger(), nullable=True),
    sa.Column('final_interest_rate_ts', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('transfer_id', sa.BigInteger(), nullable=True),
    sa.Column('finalized_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('failure_code', sa.SmallInteger(), nullable=True, comment='Failure codes for which a retry makes sense: 0) An unspecified retryable failure; 1) TIMEOUT; 2) NEWER_INTEREST_RATE; 3) RECIPIENT_IS_UNREACHABLE; 4) INSUFFICIENT_AVAILABLE_AMOUNT.'),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.CheckConstraint("attempted_at IS NULL AND coordinator_request_id IS NULL AND final_interest_rate_ts IS NULL AND amount IS NULL OR attempted_at IS NOT NULL AND coordinator_request_id IS NOT NULL AND final_interest_rate_ts IS NOT NULL AND amount IS NOT NULL AND recipient != ''"),
    sa.CheckConstraint('amount > 0'),
    sa.CheckConstraint('failed_attempts >= 0'),
    sa.CheckConstraint('failure_code IS NULL OR attempted_at IS NOT NULL'),
    sa.CheckConstraint('finalized_at IS NULL OR transfer_id IS NOT NULL'),
    sa.CheckConstraint('nominal_amount >= 2.0'),
    sa.CheckConstraint('transfer_id IS NULL OR coordinator_request_id IS NOT NULL'),
    sa.PrimaryKeyConstraint('from_collector_id', 'debtor_id', 'turn_id', 'to_creditor_id', 'is_dispatching'),
    comment="Represents a past or future attempt to transfer some amount form a given collector's account to another account, as a part of a given trading turn. More than one attempt may be made if the first attempt has failed."
    )
    with op.batch_alter_table('transfer_attempt', schema=None) as batch_op:
        batch_op.create_index('idx_transfer_coordinator_request_id', ['coordinator_request_id'], unique=True, postgresql_where=sa.text('coordinator_request_id IS NOT NULL'))
        batch_op.create_index('idx_transfer_scheduled_for', ['scheduled_for'], unique=False, postgresql_where=sa.text('scheduled_for IS NOT NULL'))

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transfer_attempt', schema=None) as batch_op:
        batch_op.drop_index('idx_transfer_scheduled_for', postgresql_where=sa.text('scheduled_for IS NOT NULL'))
        batch_op.drop_index('idx_transfer_coordinator_request_id', postgresql_where=sa.text('coordinator_request_id IS NOT NULL'))

    op.drop_table('transfer_attempt')
    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

