"""empty message

Revision ID: 88cd664f51a3
Revises: dcb810823e04
Create Date: 2024-09-21 19:16:59.266474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88cd664f51a3'
down_revision = 'dcb810823e04'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debtor_info_fetch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forced_iri', sa.String(), nullable=True))
        batch_op.drop_column('ignore_cache')

    with op.batch_alter_table('fetch_debtor_info_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forced_iri', sa.String(), nullable=True))
        batch_op.drop_column('ignore_cache')

    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fetch_debtor_info_signal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore_cache', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('forced_iri')

    with op.batch_alter_table('debtor_info_fetch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ignore_cache', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_column('forced_iri')

    # ### end Alembic commands ###


def upgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_solver():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

